### ISSUE TITLE
Env var not passed down the nix develop command

### ISSUE THREAD

**Issue by soywod** [cachix/install-nix-action#149]
I have a step that publishes my node lib to [NPM](https://www.npmjs.com/package/react-pin-field):

```yml
      - name: Publishes the lib
        working-directory: lib
        run: nix develop -c yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

This command fails because `yarn publish` cannot find the `NODE_AUTH_TOKEN` env var. If I remove the `nix develop -c` it works as expected, but I would prefer using the node version packed with nix. Any idea on how to deal with this?
