### ISSUE TITLE
Installer broken by Nix 2.14

### ISSUE THREAD

**Issue by l0b0** [cachix/install-nix-action#161]
Two separate repos with the same code:

```yaml
  test-nix-shell:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: cachix/install-nix-action@v19
      - uses: cachix/cachix-action@v12
        with:
          name: some-name
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
```

are suddenly reporting the same issue during `cachix/cachix-action@v12`:

>   Error: Action failed with error: Error: Unable to locate executable file: cachix. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
