### ISSUE TITLE
Set nixpkgs channel

### ISSUE THREAD

**Issue by Gerschtli** [cachix/install-nix-action#17]
Hey,

I really like this action, but I found myself repeatedly adding a run action to simply set a nixpkgs channel. How about adding a parameter to specify which nixpkgs channel should be used and install it, like:

```yml
- uses: cachix/install-nix-action@v6
  with:
    nixpkgs: https://nixos.org/channels/nixos-19.09
```

or maybe even shorter through prefixing the channel name with `https://nixos.org/channels/`:

```yml
- uses: cachix/install-nix-action@v6
  with:
    nixpkgs: nixos-19.09
```

which does nothing more than running:
```sh
nix-channel --add ${{ parameter.nixpkgs }} nixpkgs
nix-channel --update
```
