### ISSUE TITLE
Specify store in extra_nix_config is not work

### ISSUE THREAD

**Issue by minizilla** [cachix/install-nix-action#177]
I try to specify custom nix store location with `store = ~/nix` using `extra_nix_config`, it confirmed that the config in `/etc/nix/nix.conf` appended.

```
$ cat /etc/nix/nix.conf
max-jobs = auto
trusted-users = root runner
access-tokens = github.com=***
store = ~/nix
experimental-features = nix-command flakes
build-users-group = nixbld
```

However nix command seems to ignore the custom nix store location. For example, I try to cache nix store in `~/nix`.

The caching is works by specifying `--store ~/nix` when running `nix develop`.

```yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Nix
        uses: cachix/install-nix-action@v20
      - name: Cache Nix
        uses: actions/cache@v3
        with:
          path: ~/nix
          key: ${{ runner.os }}-nix-${{ hashFiles('flake.nix', 'flake.lock') }}
      - name: Nix develop
        run: nix --store ~/nix develop . --command echo "ok"
```

But the caching doesn't work if specifying custom store using `store = ~/nix` in `extra_nix_config`.

```yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Nix
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: store = ~/nix
      - name: Cache Nix
        uses: actions/cache@v3
        with:
          path: ~/nix
          key: ${{ runner.os }}-nix-${{ hashFiles('flake.nix', 'flake.lock') }}
      - name: Test
        run: nix develop . --command echo "ok"
```
