### ISSUE TITLE
many log lines about "Nix search path entry" not existing in @v31

### ISSUE THREAD

**Issue by cdepillabout** [cachix/install-nix-action#227]
When updating from https://github.com/cachix/install-nix-action/releases/tag/v30 to https://github.com/cachix/install-nix-action/releases/tag/v31, I'm starting to see many, many instances of the following in our GitHub Workflow logs:

```
warning: Nix search path entry '/home/runner/.nix-defexpr/channels' does not exist, ignoring
```

Our workflows look basically like this:

```yaml
      - uses: cachix/install-nix-action@v30

      - uses: cachix/cachix-action@v16
        with:
          name: our-cachix-name
          authToken: "..."

...

      - name: cabal build in nix-shell
        run: |
          nix-shell --verbose --command 'cabal build all'
```

I'm seeing the above `warning` lines when running `nix-shell`, during the Nix evaluation phase.  The message repeats over and over, many times.

I've also tried specifying a `with: {nix-path: "nixpkgs=channel:nixos-unstable"}` to the `cachix/install-nix-action@v31`, but that didn't seem to make any difference.

My guess is that this problem is related to https://github.com/NixOS/nix/pull/11079, but I didn't try to confirm this.  I don't really understand exactly what is going on in that issue, or the interactions between the `NIX_PATH` env var, and the `nix-path` setting in `nix.conf`.
