### ISSUE TITLE
NIX_PATH not set

### ISSUE THREAD

**Issue by GuillaumeDesforges** [cachix/install-nix-action#41]
In a later github action, I run a test that tries to pull the `NIX_PATH` environment variable, but it says it is not set.

```
test-mylib: NIX_PATH: getEnv: does not exist (no environment variable)
```

Is it the desired behaviour ?

**Comment by domenkozar** [comment]
Could you link the workflow?

**Comment by GuillaumeDesforges** [comment]
It is private atm, but I can give you the "equivalent":

```yaml
name: mylib CI

on: [push]

jobs:
  build:
    name: build+tests+doc
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v9
        with:
          skip_adding_nixpkgs_channel: true
      - uses: cachix/cachix-action@v6
        with:
          name: mylib
          signingKey: "${{ secrets.CACHIX_SIGNING }}"
      # Builds
      - run: nix-build nix -A mylib.components.library
      - run: nix-build nix -A mylib.components.exes
      - run: |
          echo Build tests
          TESTS_PATH=$(nix-build nix -A mylib.components.tests)
          echo Running tests
          $TESTS_PATH/bin/test-mylib
      # Build documentation and create symlink to ./result-docs
      - run: nix-build -o result-docs nix/docs
      # Deploy documentation to a github page
      - name: deploy-doc
        # Push to GitHub Pages only on master
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./result-docs
```
