### ISSUE TITLE
Flakes example from README doesn't work on macos-latest

### ISSUE THREAD

**Issue by rickynils** [cachix/install-nix-action#48]
I tried the Flakes example from the README on `macos-latest`:

```yaml
name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
    - uses: cachix/install-nix-action@v11
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20200820_4d77513/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run: nix-build
```

The installation failed with this error:

```

Run cachix/install-nix-action@v11
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   633  100   633    0     0   2370      0 --:--:-- --:--:-- --:--:--  2361

100  2593  100  2593    0     0   4343      0 --:--:-- --:--:-- --:--:--  4343
downloading Nix 3.0pre20200820_4d77513 binary tarball for x86_64-darwin from 'https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20200820_4d77513/nix-3.0pre20200820_4d77513-x86_64-darwin.tar.xz' to '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/nix-binary-tarball-unpack.XXXXXXXXXX.y9Dm5psj'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   673  100   673    0     0   2520      0 --:--:-- --:--:-- --:--:--  2520

  0 26.2M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 50 26.2M   50 13.3M    0     0  8695k      0  0:00:03  0:00:01  0:00:02 14.3M
100 26.2M  100 26.2M    0     0  12.9M      0  0:00:02  0:00:02 --:--:-- 18.8M
Note: a multi-user installation is possible. See https://nixos.org/nix/manual/#sect-multi-user-installation
Creating volume and mountpoint /nix.
/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/nix-binary-tarball-unpack.XXXXXXXXXX.y9Dm5psj/unpack/nix-3.0pre20200820_4d77513-x86_64-darwin/install: line 108: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/nix-binary-tarball-unpack.XXXXXXXXXX.y9Dm5psj/unpack/nix-3.0pre20200820_4d77513-x86_64-darwin/create-darwin-volume.sh: No such file or directory
child_process.js:642
    throw err;
    ^
```
