### ISSUE TITLE
Feature suggestion: Configure additional (non-cachix) caches

### ISSUE THREAD

**Issue by nomeata** [cachix/install-nix-action#58]
In some of my projects (using `haskell.nix`), I could make good use of the iohk cache. They have setup instructions at https://input-output-hk.github.io/haskell.nix/tutorials/getting-started/#setting-up-the-binary-cache but it’s the usual problem:

 * It requires changing an existing line in the nix config (so simply appending via the existing support is not enough)
 * It requires knowing the location of the nix config, which is something that `install-nix-action` arguably should hide.

So it would be nice to be able to say
```
    - uses: cachix/install-nix-action@v13
      with:
        extra-caches:
        - url: https://hydra.iohk.io
          key: hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ
```
and not worry about anything else.
