### ISSUE TITLE
How to use nix-env?

### ISSUE THREAD

**Issue by nomeata** [cachix/install-nix-action#59]
Maybe I am blind because it is late at night, but this doesn’t seem to work
```
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - name: "install dependencies"
      run: nix-env --install graphviz
```
The readme sound as if `nix_path` is enough to configure a channel, but `nix-env` keeps saying 
```
error: attribute 'graphviz' in selection path 'graphviz' not found
```

I could work around it with 
```
    - uses: cachix/install-nix-action@v12
    - name: "install dependencies"
      run: |
        nix-channel --add https://nixos.org/channels/nixos-20.09 nixpkgs
        nix-channel --update
        nix-env --install graphviz
```
but I have the feeling that this is too manual than what one would expect from a “install nix” action… (or mabye it just is the intended way?)
