### ISSUE TITLE
error: operation 'addTempRoot' is not supported by store

### ISSUE THREAD

**Issue by CorbanR** [cachix/install-nix-action#60]
I've been using  `cachix/install-nix-action` for a while to build and then upload to my own cache.

I've recently upgraded to the latest version of  `cachix/install-nix-action`, and am seeing a `'addTempRoot' is not supported by store`

See https://github.com/CorbanR/nixpkgs/runs/1475731991?check_suite_focus=true#step:11:54

```
      # v12
    - uses: cachix/install-nix-action@07da2520ee
      with:
        install_url: https://releases.nixos.org/nix/nix-2.3.8/install
        nix_path: nixpkgs=channel:nixpkgs-unstable
```

Where the failure is happening
```
    - name: Sign the packages
      if: (github.event_name == 'push' || github.event.inputs.deploy == 'true') && github.ref == 'refs/heads/master'
      run: |
        export NIX_SECRET_KEY_FILE="$PWD/nix-cache-priv-key.pem"
        echo "$NIX_SECRET_KEY" > "$NIX_SECRET_KEY_FILE"
        nix sign-paths -k "$NIX_SECRET_KEY_FILE"
        nix copy --to "file:///$PWD/_output/cache?compression=xz"
        nix path-info --store "file:///$PWD/_output/cache" --json | json_pp
        rm -rf "$NIX_SECRET_KEY_FILE"
      env:
        NIX_SECRET_KEY: ${{ secrets.NIX_SECRET_KEY }}
```

Any ideas? Im not actually sure if it's due to upgrading this action, or if it's an issue with the `nix` version that im using.

**Comment by domenkozar** [comment]
@CorbanR why are you setting `install_url`? 

Also, what changed between the build that failed and the build that is succeeding?

**Comment by CorbanR** [comment]
My intent with setting the `install_url` was just to make sure the version of nix, matched what I personally was using on my machine. I removed the `install_url` for now.

So now it just looks like 
This is what I upgraded to
```
   # v12
    - uses: cachix/install-nix-action@07da2520ee
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
```


This is what was working in the past(Albiet, the reason I upgraded to v12, was an error I saw recently in regards to v10(specifically the deprecation of `set-env` command))
```
    # v10
    - uses: cachix/install-nix-action@63cf434de4
```
