### ISSUE TITLE
Possible alternative for Nix w/ flakes

### ISSUE THREAD

**Issue by colinxs** [cachix/install-nix-action#75]
As an alternative to:
```
    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/lb41az54kzk6j12p81br4bczary7m145/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
```
which pins the Nix version being used, you could make use of [numtide/nix-unstable-installer](https://github.com/numtide/nix-unstable-installer) and do:
```
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/latest/download/install
          extra_nix_config: |
            experimental-features = nix-command flakes
```
to just always grab the latest successful build from Hydra.
